"""empty message

Revision ID: 1bad9b21430b
Revises: 8a2addf1465f
Create Date: 2019-05-29 06:17:36.711346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bad9b21430b'
down_revision = '8a2addf1465f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('alipay_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'alipay_no')
    # ### end Alembic commands ###
