"""empty message

Revision ID: 8a2addf1465f
Revises: a58d1efa53b1
Create Date: 2019-05-29 03:21:21.559078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2addf1465f'
down_revision = 'a58d1efa53b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('buyer_memo', sa.String(), nullable=True))
    op.add_column('order', sa.Column('buyer_message', sa.String(), nullable=True))
    op.add_column('order', sa.Column('est_con_time', sa.String(), nullable=True))
    op.add_column('order', sa.Column('seller_memo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'seller_memo')
    op.drop_column('order', 'est_con_time')
    op.drop_column('order', 'buyer_message')
    op.drop_column('order', 'buyer_memo')
    # ### end Alembic commands ###
