"""empty message

Revision ID: a58d1efa53b1
Revises: 901ff6d250b7
Create Date: 2019-05-28 04:18:32.419257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58d1efa53b1'
down_revision = '901ff6d250b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('kind', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'kind')
    # ### end Alembic commands ###
